{"name": "GET - Try to get Login with Invalid Password", "status": "broken", "statusDetails": {"message": "KeyError: '_id'\n", "trace": "  File \"C:\\Users\\Bruno Cesar Mendes\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Bruno Cesar Mendes\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features\\steps\\general.steps.py\", line 23, in step_impl\n    Login.do_request(context, request, data)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Bruno Cesar Mendes\\Documents\\GitHub\\carrefour-api-rest-tests\\features\\steps\\classes\\login.py\", line 15, in do_request\n    usuario = Usuario().do_request(context, \"GET\", \"given\").json()\n              ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Bruno Cesar Mendes\\Documents\\GitHub\\carrefour-api-rest-tests\\features\\steps\\classes\\usuario.py\", line 47, in do_request\n    id = context.given_data.json()[\"_id\"]\n         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n"}, "steps": [{"name": "Given I create a new \"usuario\"", "status": "passed", "start": 1760994657936, "stop": 1760994658550}, {"name": "When I do a \"GET\" request to \"login\" endpoint with \"invalid_password\" data", "status": "broken", "statusDetails": {"message": "KeyError: '_id'\n", "trace": "  File \"C:\\Users\\Bruno Cesar Mendes\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Bruno Cesar Mendes\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features\\steps\\general.steps.py\", line 23, in step_impl\n    Login.do_request(context, request, data)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Bruno Cesar Mendes\\Documents\\GitHub\\carrefour-api-rest-tests\\features\\steps\\classes\\login.py\", line 15, in do_request\n    usuario = Usuario().do_request(context, \"GET\", \"given\").json()\n              ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Bruno Cesar Mendes\\Documents\\GitHub\\carrefour-api-rest-tests\\features\\steps\\classes\\usuario.py\", line 47, in do_request\n    id = context.given_data.json()[\"_id\"]\n         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n"}, "start": 1760994658550, "stop": 1760994658556}, {"name": "Then the status code should be \"401\"", "status": "skipped", "start": 1760994659681, "stop": 1760994659681}, {"name": "And the \"message\" with \"Email e/ou senha inv√°lidos\" is on response body", "status": "skipped", "start": 1760994659681, "stop": 1760994659681}], "start": 1760994657936, "stop": 1760994659681, "uuid": "f5291965-425f-42d0-8a0d-7b68f7fa7ce4", "historyId": "dae4b00ab119fc9392ec577b8b69833d", "fullName": "Negative Get JWT Token Flow: GET - Try to get Login with Invalid Password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Negative Get JWT Token Flow"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}], "titlePath": ["features", "contract", "authentication", "Negative Get JWT Token Flow"]}